function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Package consumer command failed: ${ARGV}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" --install "${PROVIDER_BUILD}" --prefix "${TEST_ROOT}/prefix")
run("${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${TEST_ROOT}/build" "-DCMAKE_PREFIX_PATH=${TEST_ROOT}/prefix")
run("${CMAKE_COMMAND}" --build "${TEST_ROOT}/build")
run("${TEST_ROOT}/build/consumer")
